presentation/AppServiceMigrator/Controllers/TemplateController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace AppServiceMigrator.Controllers
{
    public class TemplateController : Controller
    {
        public IActionResult Tier1Configuration()
        {
            return View();
        }
        public IActionResult Tier2Configuration()
        {
            return View();
        }
        public IActionResult Tier3Configuration()
        {
            return View();
        }
        public IActionResult Tier4Configuration()
        {
            return View();
        }
        public IActionResult Tier5Configuration()
        {
            return View();
        }
        public IActionResult TemplateReview()
        {
            return View();
        }
    }
}

presentation/AppServiceMigrator/Views/Template/TemplateReview.cshtml
@{
    ViewData["Title"] = "TemplateReview";
}

<b>Review App Service Template</b>
<textarea rows="20" cols="150"></textarea>
<input id="submit" type="button" onclick="location.href='@Url.Action("", "Template")'"
       value="Submit" style="border:0px;background:transparent;text-decoration:none;cursor:pointer;" />

presentation/AppServiceMigrator/Views/Template/Tier1Configuration.cshtml
@{
    ViewData["Title"] = "Tier1Configuration";
}
<b>Tier1 Configuration</b>
<ul>
    <li>App Service plan.</li>
    <li>Any other related resources, like databases or storage accounts.</li>
</ul>
<input id="submit" type="button" onclick="location.href='@Url.Action("Tier2Configuration", "Template")'"
       value="Next" style="border:0px;background:transparent;text-decoration:none;cursor:pointer;" />

presentation/AppServiceMigrator/Views/Template/Tier2Configuration.cshtml
@{
    ViewData["Title"] = "Tier2Configuration";
}

<b>Tier2 Configuration</b>
<ul>
    <li>Web app</li>
    <li>Azure Application Insights instance</li>
</ul>
<input id="submit" type="button" onclick="location.href='@Url.Action("Tier3Configuration", "Template")'"
       value="Next" style="border:0px;background:transparent;text-decoration:none;cursor:pointer;" />

presentation/AppServiceMigrator/Views/Template/Tier3Configuration.cshtml
@{
    ViewData["Title"] = "Tier3Configuration";
}

<b>Tier3 Configuration</b>
<ul>
    <li>Source control</li>
    <li>MSDeploy site extension</li>
    <li>Application Insights instance</li>
</ul>
<input id="submit" type="button" onclick="location.href='@Url.Action("Tier4Configuration", "Template")'"
       value="Next" style="border:0px;background:transparent;text-decoration:none;cursor:pointer;" />

presentation/AppServiceMigrator/Views/Template/Tier4Configuration.cshtml
@{
    ViewData["Title"] = "Tier4Configuration";
}

<b>Tier4 Configuration</b>
<ul>
    <li>App Service certificate</li>
    <li>Configuration settings (connection strings, web.config values, app settings)</li>
</ul>
<input id="submit" type="button" onclick="location.href='@Url.Action("Tier5Configuration", "Template")'"
       value="Next" style="border:0px;background:transparent;text-decoration:none;cursor:pointer;" />

presentation/AppServiceMigrator/Views/Template/Tier5Configuration.cshtml
@{
    ViewData["Title"] = "Tier5Configuration";
}

<b>Tier5 Configuration</b>
<ul>
    <li>Host name bindings</li>
    <li>Site extensions</li>
</ul>
<input id="submit" type="button" onclick="location.href='@Url.Action("TemplateReview", "Template")'"
       value="Review & Submit" style="border:0px;background:transparent;text-decoration:none;cursor:pointer;" />